#!/bin/bash

set -e

# Load user configuration from .env
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found at $ENV_FILE"
    echo "Please copy .env.example to .env and configure your settings"
    exit 1
fi

set -a
source "$ENV_FILE"
set +a

# Load infrastructure configuration (generated by script 01)
if [ ! -f "$SCRIPT_DIR/infrastructure_config.sh" ]; then
    echo "Error: infrastructure_config.sh not found"
    echo "Please run ./01_create_infrastructure.sh first"
    exit 1
fi

source "$SCRIPT_DIR/infrastructure_config.sh"

echo "====================================================================="
echo "Creating IAM Roles and Policies"
echo "====================================================================="
echo ""
echo "Account ID: $AWS_ACCOUNT_ID"
echo "Region: $AWS_REGION"
echo ""

# 1. Create Textract SNS Role (allows Textract to publish to SNS)
echo "====================================================================="
echo "1. Creating Textract SNS Role: $TEXTRACT_ROLE_NAME"
echo "====================================================================="

# Trust policy for Textract
TEXTRACT_TRUST_POLICY=$(cat <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "textract.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
)

# Create or update role
if aws iam get-role --role-name $TEXTRACT_ROLE_NAME --profile $AWS_PROFILE 2>/dev/null; then
    echo "  ✓ Role '$TEXTRACT_ROLE_NAME' already exists"
else
    aws iam create-role \
        --role-name $TEXTRACT_ROLE_NAME \
        --assume-role-policy-document "$TEXTRACT_TRUST_POLICY" \
        --profile $AWS_PROFILE

    echo "  ✓ Role '$TEXTRACT_ROLE_NAME' created"
fi

# Attach SNS publish policy
TEXTRACT_SNS_POLICY=$(cat <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "sns:Publish"
      ],
      "Resource": "$SNS_TOPIC_ARN"
    }
  ]
}
EOF
)

aws iam put-role-policy \
    --role-name $TEXTRACT_ROLE_NAME \
    --policy-name TextractSNSPublishPolicy \
    --policy-document "$TEXTRACT_SNS_POLICY" \
    --profile $AWS_PROFILE

TEXTRACT_ROLE_ARN="arn:aws:iam::$AWS_ACCOUNT_ID:role/$TEXTRACT_ROLE_NAME"
echo "  ✓ Textract Role ARN: $TEXTRACT_ROLE_ARN"
echo ""

# 2. Create Lambda Initiator Role
echo "====================================================================="
echo "2. Creating Lambda Batch Initiator Role: $LAMBDA_INITIATOR_ROLE_NAME"
echo "====================================================================="

# Lambda trust policy
LAMBDA_TRUST_POLICY=$(cat <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
)

# Create role
if aws iam get-role --role-name $LAMBDA_INITIATOR_ROLE_NAME --profile $AWS_PROFILE 2>/dev/null; then
    echo "  ✓ Role '$LAMBDA_INITIATOR_ROLE_NAME' already exists"
else
    aws iam create-role \
        --role-name $LAMBDA_INITIATOR_ROLE_NAME \
        --assume-role-policy-document "$LAMBDA_TRUST_POLICY" \
        --profile $AWS_PROFILE

    echo "  ✓ Role '$LAMBDA_INITIATOR_ROLE_NAME' created"
fi

# Attach basic Lambda execution policy
aws iam attach-role-policy \
    --role-name $LAMBDA_INITIATOR_ROLE_NAME \
    --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole \
    --profile $AWS_PROFILE

# Attach custom policy for Textract, S3, and DynamoDB
# Build S3 resources list (avoid duplicates if same bucket)
if [ "$SOURCE_BUCKET" == "$OUTPUT_BUCKET" ]; then
    S3_INITIATOR_RESOURCES="\"arn:aws:s3:::${SOURCE_BUCKET}\",\"arn:aws:s3:::${SOURCE_BUCKET}/*\""
else
    S3_INITIATOR_RESOURCES="\"arn:aws:s3:::${SOURCE_BUCKET}\",\"arn:aws:s3:::${SOURCE_BUCKET}/*\""
fi

LAMBDA_INITIATOR_POLICY=$(cat <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "textract:StartDocumentAnalysis"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:ListBucket"
      ],
      "Resource": [
        $S3_INITIATOR_RESOURCES
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "dynamodb:PutItem",
        "dynamodb:GetItem",
        "dynamodb:UpdateItem"
      ],
      "Resource": "arn:aws:dynamodb:$AWS_REGION:$AWS_ACCOUNT_ID:table/$DYNAMODB_TABLE_NAME"
    },
    {
      "Effect": "Allow",
      "Action": [
        "iam:PassRole"
      ],
      "Resource": "$TEXTRACT_ROLE_ARN"
    }
  ]
}
EOF
)

aws iam put-role-policy \
    --role-name $LAMBDA_INITIATOR_ROLE_NAME \
    --policy-name LambdaInitiatorPolicy \
    --policy-document "$LAMBDA_INITIATOR_POLICY" \
    --profile $AWS_PROFILE

LAMBDA_INITIATOR_ROLE_ARN="arn:aws:iam::$AWS_ACCOUNT_ID:role/$LAMBDA_INITIATOR_ROLE_NAME"
echo "  ✓ Lambda Initiator Role ARN: $LAMBDA_INITIATOR_ROLE_ARN"
echo ""

# 3. Create Lambda Processor Role
echo "====================================================================="
echo "3. Creating Lambda Result Processor Role: $LAMBDA_PROCESSOR_ROLE_NAME"
echo "====================================================================="

# Create role
if aws iam get-role --role-name $LAMBDA_PROCESSOR_ROLE_NAME --profile $AWS_PROFILE 2>/dev/null; then
    echo "  ✓ Role '$LAMBDA_PROCESSOR_ROLE_NAME' already exists"
else
    aws iam create-role \
        --role-name $LAMBDA_PROCESSOR_ROLE_NAME \
        --assume-role-policy-document "$LAMBDA_TRUST_POLICY" \
        --profile $AWS_PROFILE

    echo "  ✓ Role '$LAMBDA_PROCESSOR_ROLE_NAME' created"
fi

# Attach basic Lambda execution policy
aws iam attach-role-policy \
    --role-name $LAMBDA_PROCESSOR_ROLE_NAME \
    --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole \
    --profile $AWS_PROFILE

# Attach custom policy for Textract, S3, DynamoDB, and SQS
# Build S3 resources list (avoid duplicates if same bucket)
if [ "$SOURCE_BUCKET" == "$OUTPUT_BUCKET" ]; then
    S3_PROCESSOR_RESOURCES="\"arn:aws:s3:::${SOURCE_BUCKET}\",\"arn:aws:s3:::${SOURCE_BUCKET}/*\""
else
    S3_PROCESSOR_RESOURCES="\"arn:aws:s3:::${SOURCE_BUCKET}\",\"arn:aws:s3:::${SOURCE_BUCKET}/*\",\"arn:aws:s3:::${OUTPUT_BUCKET}\",\"arn:aws:s3:::${OUTPUT_BUCKET}/*\""
fi

LAMBDA_PROCESSOR_POLICY=$(cat <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "textract:GetDocumentAnalysis"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:PutObject"
      ],
      "Resource": [
        $S3_PROCESSOR_RESOURCES
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "dynamodb:GetItem",
        "dynamodb:UpdateItem",
        "dynamodb:Query"
      ],
      "Resource": "arn:aws:dynamodb:$AWS_REGION:$AWS_ACCOUNT_ID:table/$DYNAMODB_TABLE_NAME"
    },
    {
      "Effect": "Allow",
      "Action": [
        "sqs:ReceiveMessage",
        "sqs:DeleteMessage",
        "sqs:GetQueueAttributes"
      ],
      "Resource": "$SQS_QUEUE_ARN"
    }
  ]
}
EOF
)

aws iam put-role-policy \
    --role-name $LAMBDA_PROCESSOR_ROLE_NAME \
    --policy-name LambdaProcessorPolicy \
    --policy-document "$LAMBDA_PROCESSOR_POLICY" \
    --profile $AWS_PROFILE

LAMBDA_PROCESSOR_ROLE_ARN="arn:aws:iam::$AWS_ACCOUNT_ID:role/$LAMBDA_PROCESSOR_ROLE_NAME"
echo "  ✓ Lambda Processor Role ARN: $LAMBDA_PROCESSOR_ROLE_ARN"
echo ""

# Save role ARNs to configuration file
echo "====================================================================="
echo "4. Updating configuration"
echo "====================================================================="

cat >> "$SCRIPT_DIR/infrastructure_config.sh" <<EOF

# IAM Roles
export TEXTRACT_ROLE_ARN="$TEXTRACT_ROLE_ARN"
export LAMBDA_INITIATOR_ROLE_ARN="$LAMBDA_INITIATOR_ROLE_ARN"
export LAMBDA_PROCESSOR_ROLE_ARN="$LAMBDA_PROCESSOR_ROLE_ARN"
EOF

echo "  ✓ Configuration updated"
echo ""

echo "====================================================================="
echo "✓ IAM Roles Created Successfully!"
echo "====================================================================="
echo ""
echo "Summary:"
echo "  - Textract SNS Role: $TEXTRACT_ROLE_ARN"
echo "  - Lambda Initiator Role: $LAMBDA_INITIATOR_ROLE_ARN"
echo "  - Lambda Processor Role: $LAMBDA_PROCESSOR_ROLE_ARN"
echo ""
echo "Waiting 10 seconds for IAM roles to propagate..."
sleep 10
echo ""
echo "Next step:"
echo "  Run: ./03_deploy_lambdas.sh"
echo ""
