#!/bin/bash

set -e

# Load user configuration from .env
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found at $ENV_FILE"
    echo "Please copy .env.example to .env and configure your settings"
    exit 1
fi

set -a
source "$ENV_FILE"
set +a

# Load infrastructure configuration (generated by script 01)
if [ ! -f "$SCRIPT_DIR/infrastructure_config.sh" ]; then
    echo "Error: infrastructure_config.sh not found"
    echo "Please run ./01_create_infrastructure.sh first"
    exit 1
fi

source "$SCRIPT_DIR/infrastructure_config.sh"

LAMBDA_DIR="$(dirname "$SCRIPT_DIR")"

echo "====================================================================="
echo "Deploying Lambda Functions"
echo "====================================================================="
echo ""
echo "Lambda Directory: $LAMBDA_DIR"
echo "Region: $AWS_REGION"
echo ""

# 1. Deploy Lambda Batch Initiator
echo "====================================================================="
echo "1. Deploying Lambda: $LAMBDA_INITIATOR_NAME"
echo "====================================================================="

INITIATOR_ZIP="$LAMBDA_DIR/lambda_batch_initiator.zip"

# Package Lambda 1 with config.py
cd "$LAMBDA_DIR"
rm -f lambda_batch_initiator.zip
zip -q lambda_batch_initiator.zip lambda_batch_initiator.py config.py
echo "  ✓ Package created: $INITIATOR_ZIP"

# Create or update Lambda function
if aws lambda get-function --function-name $LAMBDA_INITIATOR_NAME --profile $AWS_PROFILE --region $AWS_REGION 2>/dev/null; then
    echo "  Updating existing Lambda function..."
    aws lambda update-function-code \
        --function-name $LAMBDA_INITIATOR_NAME \
        --zip-file fileb://$INITIATOR_ZIP \
        --profile $AWS_PROFILE \
        --region $AWS_REGION > /dev/null

    # Update configuration
    aws lambda update-function-configuration \
        --function-name $LAMBDA_INITIATOR_NAME \
        --timeout $LAMBDA_INITIATOR_TIMEOUT \
        --memory-size $LAMBDA_INITIATOR_MEMORY \
        --runtime $LAMBDA_RUNTIME \
        --environment "Variables={SOURCE_BUCKET=$SOURCE_BUCKET,OUTPUT_BUCKET=$OUTPUT_BUCKET,OUTPUT_PREFIX=$OUTPUT_PREFIX,AWS_REGION=$AWS_REGION,DYNAMODB_TABLE_NAME=$DYNAMODB_TABLE_NAME}" \
        --profile $AWS_PROFILE \
        --region $AWS_REGION > /dev/null

    echo "  ✓ Lambda function updated"
else
    echo "  Creating new Lambda function..."
    aws lambda create-function \
        --function-name $LAMBDA_INITIATOR_NAME \
        --runtime $LAMBDA_RUNTIME \
        --role $LAMBDA_INITIATOR_ROLE_ARN \
        --handler lambda_batch_initiator.lambda_handler \
        --zip-file fileb://$INITIATOR_ZIP \
        --timeout $LAMBDA_INITIATOR_TIMEOUT \
        --memory-size $LAMBDA_INITIATOR_MEMORY \
        --environment "Variables={SOURCE_BUCKET=$SOURCE_BUCKET,OUTPUT_BUCKET=$OUTPUT_BUCKET,OUTPUT_PREFIX=$OUTPUT_PREFIX,AWS_REGION=$AWS_REGION,DYNAMODB_TABLE_NAME=$DYNAMODB_TABLE_NAME}" \
        --profile $AWS_PROFILE \
        --region $AWS_REGION > /dev/null

    echo "  ✓ Lambda function created"
fi

echo ""

# 2. Deploy Lambda Result Processor
echo "====================================================================="
echo "2. Deploying Lambda: $LAMBDA_PROCESSOR_NAME"
echo "====================================================================="

PROCESSOR_ZIP="$LAMBDA_DIR/lambda_result_processor.zip"

# Package Lambda 2 with config.py
cd "$LAMBDA_DIR"
rm -f lambda_result_processor.zip
zip -q lambda_result_processor.zip lambda_result_processor.py config.py
echo "  ✓ Package created: $PROCESSOR_ZIP"

# Create or update Lambda function
if aws lambda get-function --function-name $LAMBDA_PROCESSOR_NAME --profile $AWS_PROFILE --region $AWS_REGION 2>/dev/null; then
    echo "  Updating existing Lambda function..."
    aws lambda update-function-code \
        --function-name $LAMBDA_PROCESSOR_NAME \
        --zip-file fileb://$PROCESSOR_ZIP \
        --profile $AWS_PROFILE \
        --region $AWS_REGION > /dev/null

    # Update configuration
    aws lambda update-function-configuration \
        --function-name $LAMBDA_PROCESSOR_NAME \
        --timeout $LAMBDA_PROCESSOR_TIMEOUT \
        --memory-size $LAMBDA_PROCESSOR_MEMORY \
        --runtime $LAMBDA_RUNTIME \
        --environment "Variables={SOURCE_BUCKET=$SOURCE_BUCKET,OUTPUT_BUCKET=$OUTPUT_BUCKET,OUTPUT_PREFIX=$OUTPUT_PREFIX,AWS_REGION=$AWS_REGION,DYNAMODB_TABLE_NAME=$DYNAMODB_TABLE_NAME}" \
        --profile $AWS_PROFILE \
        --region $AWS_REGION > /dev/null

    echo "  ✓ Lambda function updated"
else
    echo "  Creating new Lambda function..."
    aws lambda create-function \
        --function-name $LAMBDA_PROCESSOR_NAME \
        --runtime $LAMBDA_RUNTIME \
        --role $LAMBDA_PROCESSOR_ROLE_ARN \
        --handler lambda_result_processor.lambda_handler \
        --zip-file fileb://$PROCESSOR_ZIP \
        --timeout $LAMBDA_PROCESSOR_TIMEOUT \
        --memory-size $LAMBDA_PROCESSOR_MEMORY \
        --environment "Variables={SOURCE_BUCKET=$SOURCE_BUCKET,OUTPUT_BUCKET=$OUTPUT_BUCKET,OUTPUT_PREFIX=$OUTPUT_PREFIX,AWS_REGION=$AWS_REGION,DYNAMODB_TABLE_NAME=$DYNAMODB_TABLE_NAME}" \
        --profile $AWS_PROFILE \
        --region $AWS_REGION > /dev/null

    echo "  ✓ Lambda function created"
fi

echo ""

# Wait for Lambda functions to be ready
echo "====================================================================="
echo "3. Waiting for Lambda functions to be ready"
echo "====================================================================="

echo "  Waiting for $LAMBDA_INITIATOR_NAME..."
aws lambda wait function-active \
    --function-name $LAMBDA_INITIATOR_NAME \
    --profile $AWS_PROFILE \
    --region $AWS_REGION

echo "  ✓ $LAMBDA_INITIATOR_NAME is ready"

echo "  Waiting for $LAMBDA_PROCESSOR_NAME..."
aws lambda wait function-active \
    --function-name $LAMBDA_PROCESSOR_NAME \
    --profile $AWS_PROFILE \
    --region $AWS_REGION

echo "  ✓ $LAMBDA_PROCESSOR_NAME is ready"
echo ""

# Get Lambda ARNs
INITIATOR_LAMBDA_ARN=$(aws lambda get-function \
    --function-name $LAMBDA_INITIATOR_NAME \
    --profile $AWS_PROFILE \
    --region $AWS_REGION \
    --query 'Configuration.FunctionArn' \
    --output text)

PROCESSOR_LAMBDA_ARN=$(aws lambda get-function \
    --function-name $LAMBDA_PROCESSOR_NAME \
    --profile $AWS_PROFILE \
    --region $AWS_REGION \
    --query 'Configuration.FunctionArn' \
    --output text)

# Save Lambda ARNs to configuration
cat >> "$SCRIPT_DIR/infrastructure_config.sh" <<EOF

# Lambda Functions
export INITIATOR_LAMBDA_ARN="$INITIATOR_LAMBDA_ARN"
export PROCESSOR_LAMBDA_ARN="$PROCESSOR_LAMBDA_ARN"
EOF

echo "====================================================================="
echo "✓ Lambda Deployment Complete!"
echo "====================================================================="
echo ""
echo "Summary:"
echo "  - Batch Initiator: $INITIATOR_LAMBDA_ARN"
echo "  - Result Processor: $PROCESSOR_LAMBDA_ARN"
echo ""
echo "Next step:"
echo "  Run: ./04_configure_triggers.sh"
echo ""
