#!/bin/bash

set -e

# Load user configuration from .env
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found at $ENV_FILE"
    echo "Please copy .env.example to .env and configure your settings"
    exit 1
fi

set -a
source "$ENV_FILE"
set +a

# Load infrastructure configuration (generated by script 01)
if [ ! -f "$SCRIPT_DIR/infrastructure_config.sh" ]; then
    echo "Error: infrastructure_config.sh not found"
    echo "Please run ./01_create_infrastructure.sh first"
    exit 1
fi

source "$SCRIPT_DIR/infrastructure_config.sh"

echo "====================================================================="
echo "Configuring Lambda Triggers"
echo "====================================================================="
echo ""

# Configure SQS as event source for Lambda Result Processor
echo "====================================================================="
echo "1. Creating SQS Event Source Mapping for Lambda"
echo "====================================================================="

# Check if mapping already exists
EXISTING_MAPPING=$(aws lambda list-event-source-mappings \
    --function-name $LAMBDA_PROCESSOR_NAME \
    --profile $AWS_PROFILE \
    --region $AWS_REGION \
    --query "EventSourceMappings[?EventSourceArn=='$SQS_QUEUE_ARN'].UUID" \
    --output text)

if [ -n "$EXISTING_MAPPING" ]; then
    echo "  ✓ Event source mapping already exists: $EXISTING_MAPPING"
    echo "  Updating mapping..."

    aws lambda update-event-source-mapping \
        --uuid $EXISTING_MAPPING \
        --batch-size 10 \
        --profile $AWS_PROFILE \
        --region $AWS_REGION > /dev/null

    echo "  ✓ Mapping updated"
else
    echo "  Creating new event source mapping..."

    MAPPING_UUID=$(aws lambda create-event-source-mapping \
        --function-name $LAMBDA_PROCESSOR_NAME \
        --event-source-arn $SQS_QUEUE_ARN \
        --batch-size 10 \
        --enabled \
        --profile $AWS_PROFILE \
        --region $AWS_REGION \
        --query UUID \
        --output text)

    echo "  ✓ Event source mapping created: $MAPPING_UUID"
fi

echo ""

# Save mapping UUID to configuration
cat >> "$SCRIPT_DIR/infrastructure_config.sh" <<EOF

# Event Source Mapping
export EVENT_SOURCE_MAPPING_UUID="$EXISTING_MAPPING"
EOF

echo "====================================================================="
echo "✓ Trigger Configuration Complete!"
echo "====================================================================="
echo ""
echo "Summary:"
echo "  - SQS Queue: $SQS_QUEUE_ARN"
echo "  - Lambda Function: $LAMBDA_PROCESSOR_NAME"
echo "  - Batch Size: 10 messages"
echo ""
echo "Next step:"
echo "  Run: ./05_process_batches.sh"
echo ""
