#!/bin/bash

set -e

# Load user configuration from .env
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found at $ENV_FILE"
    echo "Please copy .env.example to .env and configure your settings"
    exit 1
fi

set -a
source "$ENV_FILE"
set +a

# Load infrastructure configuration (generated by script 01)
if [ ! -f "$SCRIPT_DIR/infrastructure_config.sh" ]; then
    echo "Error: infrastructure_config.sh not found"
    echo "Please run ./01_create_infrastructure.sh first"
    exit 1
fi

source "$SCRIPT_DIR/infrastructure_config.sh"

echo "====================================================================="
echo "Processing Batches with Textract"
echo "====================================================================="
echo ""
echo "Source Bucket: $SOURCE_BUCKET"
echo "Total Batches: $TOTAL_BATCHES (batch-1 through batch-$TOTAL_BATCHES)"
echo ""

# Function to invoke Lambda for a batch
process_batch() {
    local batch_num=$1
    local batch_prefix="${BATCH_PREFIX_PATTERN}${batch_num}/"

    echo "Processing: $batch_prefix"

    # Create payload
    PAYLOAD=$(cat <<EOF
{
  "bucket_name": "$SOURCE_BUCKET",
  "batch_prefix": "$batch_prefix",
  "sns_topic_arn": "$SNS_TOPIC_ARN",
  "textract_role_arn": "$TEXTRACT_ROLE_ARN"
}
EOF
)

    # Invoke Lambda
    aws lambda invoke \
        --function-name $LAMBDA_INITIATOR_NAME \
        --payload "$PAYLOAD" \
        --cli-binary-format raw-in-base64-out \
        --profile $AWS_PROFILE \
        --region $AWS_REGION \
        /tmp/batch-${batch_num}-response.json > /dev/null

    # Show response
    cat /tmp/batch-${batch_num}-response.json | python3 -m json.tool
    echo ""
}

# Check if user wants to process all batches or specific ones
if [ "$1" == "all" ]; then
    echo "====================================================================="
    echo "Processing all batches (batch-1 through batch-$TOTAL_BATCHES)"
    echo "====================================================================="
    echo ""

    read -p "This will process all $TOTAL_BATCHES batches. Continue? (yes/no): " CONFIRM

    if [ "$CONFIRM" != "yes" ]; then
        echo "Cancelled."
        exit 0
    fi

    echo ""

    for i in $(seq 1 $TOTAL_BATCHES); do
        echo "-------------------------------------------------------------------"
        echo "Batch $i of $TOTAL_BATCHES"
        echo "-------------------------------------------------------------------"
        process_batch $i

        # Wait between batches to avoid throttling
        if [ $i -lt $TOTAL_BATCHES ]; then
            echo "Waiting 60 seconds before next batch..."
            sleep 60
        fi
    done

elif [ -n "$1" ]; then
    # Process specific batch
    echo "====================================================================="
    echo "Processing single batch: ${BATCH_PREFIX_PATTERN}$1"
    echo "====================================================================="
    echo ""

    process_batch $1

else
    # Show usage
    echo "Usage:"
    echo "  $0 all              - Process all $TOTAL_BATCHES batches (${BATCH_PREFIX_PATTERN}1 to ${BATCH_PREFIX_PATTERN}$TOTAL_BATCHES)"
    echo "  $0 <batch_number>   - Process a specific batch (e.g., $0 1)"
    echo ""
    echo "Examples:"
    echo "  $0 1        # Process ${BATCH_PREFIX_PATTERN}1 only"
    echo "  $0 all      # Process all batches"
    echo ""
    exit 1
fi

echo "====================================================================="
echo "✓ Batch Processing Initiated!"
echo "====================================================================="
echo ""
echo "What happens next:"
echo "  1. Textract processes each PDF asynchronously (5-30 seconds each)"
echo "  2. Textract sends completion notifications to SNS"
echo "  3. SNS forwards to SQS queue"
echo "  4. Lambda result processor retrieves and saves results"
echo "  5. Results saved to: s3://$OUTPUT_BUCKET/$OUTPUT_PREFIX"
echo ""
echo "To monitor progress:"
echo "  - Check Lambda logs: aws logs tail /aws/lambda/$LAMBDA_PROCESSOR_NAME --follow --profile $AWS_PROFILE"
echo "  - Check DynamoDB: aws dynamodb scan --table-name $DYNAMODB_TABLE_NAME --profile $AWS_PROFILE"
echo "  - Check SQS queue: aws sqs get-queue-attributes --queue-url $SQS_QUEUE_URL --attribute-names All --profile $AWS_PROFILE"
echo ""
echo "Results will be stored for 7 days in Textract."
echo ""
