#!/bin/bash
# Auto-generated by 01_create_infrastructure.sh
# Generated at: Fri Nov  7 09:12:23 CST 2025

export AWS_ACCOUNT_ID="694676321662"
export AWS_REGION="us-east-1"
export AWS_PROFILE="saba"
export SNS_TOPIC_ARN="arn:aws:sns:us-east-1:694676321662:textract-completion-topic"
export SQS_QUEUE_URL="https://sqs.us-east-1.amazonaws.com/694676321662/textract-results-queue"
export SQS_QUEUE_ARN="arn:aws:sqs:us-east-1:694676321662:textract-results-queue"
export SUBSCRIPTION_ARN="arn:aws:sns:us-east-1:694676321662:textract-completion-topic:61d332ba-ef76-4a15-91eb-e38788d9f1cb"

# IAM Roles
export TEXTRACT_ROLE_ARN="arn:aws:iam::694676321662:role/textract-sns-role"
export LAMBDA_INITIATOR_ROLE_ARN="arn:aws:iam::694676321662:role/lambda-textract-initiator-role"
export LAMBDA_PROCESSOR_ROLE_ARN="arn:aws:iam::694676321662:role/lambda-textract-processor-role"

# Lambda Functions
export INITIATOR_LAMBDA_ARN="arn:aws:lambda:us-east-1:694676321662:function:textract-batch-initiator"
export PROCESSOR_LAMBDA_ARN="arn:aws:lambda:us-east-1:694676321662:function:textract-result-processor"

# Event Source Mapping
export EVENT_SOURCE_MAPPING_UUID=""
